base: ..
variable:
  config: config/variables.yaml
  schema: config/variables-schema.json
  source: src/imono/schemas/variables.ts
plan:
  ddd:
    name: DDD
    actions:
      - name: model directory
        path: src/models/foo
        type: directory
      - name: remove
        path: src/models/foo
        type: remove
      - name: model
        key: models
        path: src/models/{{key}}.ts
        type: ./src/imono/actions/model-action
