generators:
  ddd:
    name: DDD
    actions:
      -
        name: model directory
        path: src/models
        type: directory
      -
        name: model
        path: src/models/{{name}}.ts
        type: model 