models:
  base:
    desc: Base
    attributes:
      id:
        desc: ID
        type: string
        optional: false
  animal:
    desc: Animal
    base: base
    attributes:
      name:
        desc: Name
        type: string
        optional: false
  family:
    base: base
    attributes:
      name:
        desc: Name
        type: string
        optional: false
      attr1:
        desc: Name
        type: ${model.animal}
        optional: false
    desc: |
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
      Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
      natoque penatibus et magnis dis parturient montes, nascetur
      ridiculus mus. Donec quam felis, ultricies nec, pellentesque
      eu, pretium quis, sem. Nulla consequat massa quis enim.
      Donec pede justo, fringilla vel,