models:
  base:
    attributes:
      id:
        type: string
        optional: true
  animal:
    base: base
    attributes:
      name: string
  family:
    base: base
    attributes:
      name:
        type: string
      attr1:
        type: ${model.animal}
    desc: |
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
      Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
      natoque penatibus et magnis dis parturient montes, nascetur
      ridiculus mus. Donec quam felis, ultricies nec, pellentesque
      eu, pretium quis, sem. Nulla consequat massa quis enim.
      Donec pede justo, fringilla vel,